kind: helm-release
apiVersion: 1.0
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/nifi
  set:
    image:
      tag: $(tag)
      pullPolicy: Never
    disableProbes: true
    ingress:
      hosts:
      # This expands to [space.s.]nifi.<guid>.<region>.aksapp.io
      - $(spacePrefix)nifi$(hostSuffix)
configurations:
  develop:
    build:
      useGitIgnore: true