version: '3.6'

services:

## docker run -it --rm -p 8080:8080 -e NIFI_WEB_HTTP_HOST=tmac-devops1681939944003.australiaeast.cloudapp.azure.com -v nifi:/tmac fusenifi
  nifi:
    image: tmacregistry-tmacomms.azurecr.io/tmacomms/fuse-nifi:latest
    #apache/nifi:1.5.0  
    # 'tmacregistry-tmacomms.azurecr.io/tmacomms/fuse-nifi:latest'
#    network_mode: "host"
    build: 
      context: .
      dockerfile: Dockerfile
    hostname: nifi-dev.tmacomms.com
    ports:
      - 9443:9443/tcp      
      #- 8443/tcp
    labels:
      io.rancher.container.hostname_override: nifi15
      io.rancher.container.pull_image: always
    environment:
      - CONF_INTERVAL=10
      - EVSENVIRONMENT=development
      - NIFI_WEB_HTTPS_HOST=nifi-dev.tmacomms.com
      - NIFI_WEB_HTTPS_PORT=9443
#      - NIFI_REMOTE_INPUT_HOST=localhost
      - EVS_SERVICEDNS=nifi-dev.tmacomms.com
      #- NIFI_REMOTE_INPUT_SOCKET_PORT=-10000
      - NIFI_HOME=/opt/nifi/nifi-1.7.0
    volumes:
     - nifidata:/opt/nifi/nifi-1.7.0/work 
     - nifitoolkit:/toolkit 
    links:
      - registry

    #restart: never
    privileged: true
    stdin_open: true
    tty: true
  registry:
   image: tmacregistry-tmacomms.azurecr.io/tmacomms/fuse-nifiregistry:latest
   build: 
    context: .
    dockerfile: Dockerfile.registry
   ports:
      - 18080:18080/tcp    
   environment:
      - CONF_INTERVAL=10
      - EVSENVIRONMENT=development
      - NIFI_WEB_HTTPS_HOST=nifiregistry-dev.tmacomms.com  
      - NIFI_WEB_HTTPS_PORT=9443
      - EVS_SERVICEDNS=nifi-dev.tmacomms.com      
   privileged: true
   stdin_open: true
   tty: true
  schemaregistry:
   image: tmacregistry-tmacomms.azurecr.io/tmacomms/fuse-schemaregistry:latest
   build: 
    context: .
    dockerfile: Dockerfile.schemaregistry
   ports:
      - 9090:9090/tcp    
   environment:
      - CONF_INTERVAL=10
      - EVSENVIRONMENT=development
      - NIFI_WEB_HTTPS_HOST=nifiregistry-dev.tmacomms.com  
      - NIFI_WEB_HTTPS_PORT=9443
      - EVS_SERVICEDNS=nifi-dev.tmacomms.com      
   privileged: true
   stdin_open: true
   tty: true   


volumes:
  nificonfig:
  nifidata:
  nifitoolkit:
