# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  pullPolicy: IfNotPresent
service:
  name: nifi
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    #cpu: 100m
    memory: 2Gi
  requests:
    #cpu: 100m
    memory: 2Gi
